// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUvmSWOfqWY0CDEpsItwcfxghBl9YFpZw',
    appId: '1:999195876722:web:6f38cb361f193d47a0d1eb',
    messagingSenderId: '999195876722',
    projectId: 'medicament-d8e43',
    authDomain: 'medicament-d8e43.firebaseapp.com',
    storageBucket: 'medicament-d8e43.appspot.com',
    measurementId: 'G-D8GRXJS87Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEQKxCSaNpAiLdvMBBxvyRn2psX8iIDD0',
    appId: '1:999195876722:android:9f1e961c3b53c3b9a0d1eb',
    messagingSenderId: '999195876722',
    projectId: 'medicament-d8e43',
    storageBucket: 'medicament-d8e43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1ehr88X2_L0Z5HnOPvfB9v72LUbaUMPw',
    appId: '1:999195876722:ios:b7d41c167b5c58b7a0d1eb',
    messagingSenderId: '999195876722',
    projectId: 'medicament-d8e43',
    storageBucket: 'medicament-d8e43.appspot.com',
    iosBundleId: 'com.example.minerestoran',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1ehr88X2_L0Z5HnOPvfB9v72LUbaUMPw',
    appId: '1:999195876722:ios:b7d41c167b5c58b7a0d1eb',
    messagingSenderId: '999195876722',
    projectId: 'medicament-d8e43',
    storageBucket: 'medicament-d8e43.appspot.com',
    iosBundleId: 'com.example.minerestoran',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUvmSWOfqWY0CDEpsItwcfxghBl9YFpZw',
    appId: '1:999195876722:web:7b6b6904fe359c5ba0d1eb',
    messagingSenderId: '999195876722',
    projectId: 'medicament-d8e43',
    authDomain: 'medicament-d8e43.firebaseapp.com',
    storageBucket: 'medicament-d8e43.appspot.com',
    measurementId: 'G-YEQ8LEKS0S',
  );
}
